AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MonthlyBudget:
    Type: 'AWS::Budgets::Budget'
    Properties:
      Budget:
        BudgetName: 'MonthlyBudget'
        BudgetLimit:
          Amount: 20  # Set your budget limit here
          Unit: 'USD'
        TimeUnit: 'MONTHLY'
        BudgetType: 'COST'
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: 'ACTUAL'
            ComparisonOperator: 'GREATER_THAN'
            Threshold: 3
            ThresholdType: 'PERCENTAGE'
          Subscribers:
            - SubscriptionType: 'EMAIL'
              Address: 'gmerritt@berkeley.edu'
            - SubscriptionType: 'EMAIL'
              Address: 'gmerritt@eecs.berkeley.edu'
        - Notification:
            NotificationType: 'ACTUAL'
            ComparisonOperator: 'GREATER_THAN'
            Threshold: 25
            ThresholdType: 'PERCENTAGE'
          Subscribers:
            - SubscriptionType: 'EMAIL'
              Address: 'gmerritt@berkeley.edu'
            - SubscriptionType: 'EMAIL'
              Address: 'gmerritt@eecs.berkeley.edu'
        - Notification:
            NotificationType: 'ACTUAL'
            ComparisonOperator: 'GREATER_THAN'
            Threshold: 50
            ThresholdType: 'PERCENTAGE'
          Subscribers:
            - SubscriptionType: 'EMAIL'
              Address: 'gmerritt@berkeley.edu'
            - SubscriptionType: 'EMAIL'
              Address: 'gmerritt@eecs.berkeley.edu'
        - Notification:
            NotificationType: 'ACTUAL'
            ComparisonOperator: 'GREATER_THAN'
            Threshold: 75
            ThresholdType: 'PERCENTAGE'
          Subscribers:
            - SubscriptionType: 'EMAIL'
              Address: 'gmerritt@berkeley.edu'
            - SubscriptionType: 'EMAIL'
              Address: 'gmerritt@eecs.berkeley.edu'
            - SubscriptionType: 'EMAIL'
              Address: 'larsrohr@eecs.berkeley.edu'
              